# Generated by Django 5.0.1 on 2024-01-14 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0002_producto_descripcion_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
    ]
