# Generated by Django 5.0.1 on 2024-01-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0003_remove_producto_descripcion_remove_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('categoria', models.CharField(max_length=32)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=64)),
            ],
        ),
    ]
