# Generated by Django 5.0.1 on 2024-01-14 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendaApp', '0004_solicitudes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Solicitudes',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('guitarras', 'Guitarras'), ('baterias', 'Baterías'), ('bajos', 'Bajos'), ('microfonos', 'Micrófonos')], default='guitarras', max_length=32),
        ),
    ]
